all: Jabberook.c
	gcc -Ofast Jabberook.c -o ../bin/all/Jabberook
allwin: Jabberook.c
	mingw32-gcc -Ofast Jabberook.c -o ../bin/all/Jabberook.exe
debug: Jabberook.c
	gcc Jabberook.c -o ../bin/debug/Jabberook
debugwin: Jabberook.c
	mingw32-gcc Jabberook.c -o ../bin/debug/Jabberook.exe