all: bbce.c
	gcc -Ofast bbce.c -o ../bin/all/bbce
allwin: bbce.c
	mingw32-gcc -Ofast bbce.c -o ../bin/all/bbce.exe
debug: bbce.c
	gcc bbce.c -o ../bin/debug/bbce
debugwin: bbce.c
	mingw32-gcc bbce.c -o ../bin/debug/bbce.exe